brancz/kubernetes-grafana

- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/kubernetes-capacity-planning-dashboard.jsonnet
- src/kubernetes-jsonnet/grafana/grafana-dashboard-definitions.jsonnet
For now I've added the first 2 rows of the dashboard. The rest will follow tomorrow.
Closes #1
> Create Capacity Planning dashboard

- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/kubernetes-kubelet-dashboard.jsonnet
- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/promgrafonnet/numbersinglestat.libsonnet
- src/kubernetes-jsonnet/grafana/grafana-dashboard-definitions.jsonnet
I've created this Kubelet dashboard for our internal purposes. I thought it might be good practice to recreate with grafonnet-lib, so here we go:
> Create Kubelet Dashboard

- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/pods-dashboard.jsonnet
- src/kubernetes-jsonnet/grafana/grafana-dashboard-definitions.jsonnet
Sadly the legend formatting for those to be a table with the current and avg values seems to be somehow broken. I can't find what's going on right now. PTAL.
> Create Pods Dashboard

- fmt.sh
- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/deployments-dashboard.jsonnet
- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/kubernetes-cluster-health-dashboard.jsonnet
- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/kubernetes-cluster-status-dashboard.jsonnet
- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/nodes.jsonnet
- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/pods-dashboard.jsonnet
- src/kubernetes-jsonnet/grafana/configs/dashboard-sources/dashboards.jsonnet
- src/kubernetes-jsonnet/grafana/configs/datasources/prometheus.jsonnet
- src/kubernetes-jsonnet/grafana/grafana-dashboard-definitions.jsonnet
- src/kubernetes-jsonnet/grafana/grafana-dashboards.jsonnet
- src/kubernetes-jsonnet/grafana/grafana-datasources.jsonnet
- src/kubernetes-jsonnet/grafana/grafana-deployment.jsonnet
Addtionally I've already formatted all files.
> Create fmt.sh to format all jsonnet files

- src/kubernetes-jsonnet/grafana/grafana-deployment.libsonnet
> Bump grafana version to 5.0.3

- example.jsonnet
- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/kubernetes-control-plane-status-dashboard.libsonnet
- src/kubernetes-jsonnet/grafana/grafana-dashboard-definitions.libsonnet
Adding the Kubernetes control plane status dashboard back.
@metalmatze
> Control plane status

- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/kubernetes-resource-requests-dashboard.libsonnet
- src/kubernetes-jsonnet/grafana/grafana-dashboard-definitions.libsonnet
> Resource requests dashboard

- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/statefulset-dashboard.libsonnet
- src/kubernetes-jsonnet/grafana/grafana-dashboard-definitions.libsonnet
With this and #14 we will have completed the transition from the old kube-prometheus stack.
@metalmatze
> dashboards: Add statefulset dashboard

- README.md
- example-with-mixin.jsonnet
- grafana/grafana.libsonnet
> Move all config into `_config`

- grafana/grafana.libsonnet
> Fix editable field for datasource

- README.md
- examples/plugins.jsonnet
- grafana/grafana.libsonnet
Closes #33
@metalmatze 
cc @nroitero
> Add ability to specify plugins to install

- grafana/grafana.libsonnet
> Bump Grafana version to 5.2.1

- grafana/configs/dashboard-sources/dashboards.libsonnet
Fixes #37 
@metalmatze 
cc @KlavsKlavsen
> Update schema of dashboard provisioning

- README.md
- examples/custom-ini.jsonnet
- grafana/grafana.libsonnet
Allow ingesting `ldap.toml` plain text file to `grafana-config` secret.
> Add LDAP functionality

- grafana/grafana.libsonnet
Hi, no major change here except going with the latest grafana version
> Update Grafana Version

- README.md
- examples/dashboard-definition.jsonnet
> Add dashboard example

- grafana/grafana.libsonnet
> Add `app` label to grafana service

- grafana/grafana.libsonnet
> Ensure only deployed on Linux nodes

- grafana/grafana.libsonnet
Related to https://github.com/coreos/kube-prometheus/pull/270
> Bump Grafana version

- examples/basic-with-image-renderer.jsonnet
- grafana/grafana.libsonnet
- grafana/jsonnetfile.json
Creates a sidecar modeled after - https://grafana.com/docs/grafana/latest/administration/image_rendering/#remote-rendering-service
> Add sidecar for image rendering

- grafana/jsonnetfile.json
> grafana/jsonnetfile.json: Make jb 0.2 compatible

- grafana/grafana.libsonnet
> Create Default folder provider only if needed

- grafana/grafana.libsonnet
> Trigger deployment rolling-update on config changes

- grafana/grafana.libsonnet
> Link configuration for resource to container

- grafana/grafana.libsonnet
This allows easy overriding labels in projects using kubernetes-grafana as a library.
> add recommended kubernetes labels to all objects

- grafana/grafana.libsonnet
> grafana: do not encode configs and use stringData type

- grafana/grafana.libsonnet
I didn't see any tests in other merged PRs (or in the repo,) but does any thing in the README need changed in the "config customization" section?
> Set default timezone to UTC via config file
