brancz/kubernetes-grafana

- .editorconfig
I think it could be helpful to have this editorconfig for users that have no experience with jsonnet.
> Create .editorconfig with 4 spaces for jsonnet

- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/deployments-dashboard.libsonnet
This is the last dashboard which has had these prefixes.
> Remove exported_ prefix from all namespaces in deployments dashboard

- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/deployments-dashboard.libsonnet
- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/promgrafonnet/numbersinglestat.libsonnet
- src/kubernetes-jsonnet/grafana/configs/dashboard-definitions/statefulset-dashboard.libsonnet
Small improvement (which was previously present in the kube-prometheus dashboards) that displays the units of the cpu, memory and network panels of deployment and statefulset dashboards.
@metalmatze
> dashboards: Add units to statefulset and deployment dashboards

- grafana/grafana.libsonnet
This fixes the version of the Grafana datasource provisioning spec to the current API version. Previously Grafana printed a deprecation warning due to this missing.
@metalmatze
> Fix Grafana datasource provisioning schema version

- grafana/grafana.libsonnet
Per [kube-prometheus PR](https://github.com/coreos/prometheus-operator/pull/2026#discussion_r226842700) it would be preferable to have pluses all the way down for `_config+::` items.
Currently if we try to use + we get the error:
`RUNTIME ERROR: binary operator + requires matching types, got null and object.`
For example, instead of:
```
_config+:: {
namespace: 'monitoring-grafana',
grafana+:: {
config: {
```
Do:
```
_config+:: {
namespace: 'monitoring-grafana',
grafana+:: {
config+: {
```
Prometheus and Alertmanager in the kube-prometheus both require use of `+` to extend `_config`.
> Enable Grafana config merging

- grafana/grafana.libsonnet
This PR adds a Readiness Probe to the Grafana container which hits it's `/api/health`
endpoint. Such a probe can be used by load balancers to exclude unhealthy instances
from receiving traffic.
Fixes #49
> Add Readiness Probe to Grafana container

- grafana/grafana.libsonnet
When I try to build and deploy `prometheus-operator` with the following `example.json` file, I found my grafana still access the prometheus with `prometheus-k8s.monitoring.svc:9090` instead of `prometheus-k8s.kube-system.svc:9090`. I think this PR might fix that.
```
$ cat example.json 
local kp = (import 'kube-prometheus/kube-prometheus.libsonnet') + {
_config+:: {
namespace: 'kube-system',
},
};
{ ['00namespace-' + name]: kp.kubePrometheus[name] for name in std.objectFields(kp.kubePrometheus) } +
{ ['0prometheus-operator-' + name]: kp.prometheusOperator[name] for name in std.objectFields(kp.prometheusOperator) } +
{ ['node-exporter-' + name]: kp.nodeExporter[name] for name in std.objectFields(kp.nodeExporter) } +
{ ['kube-state-metrics-' + name]: kp.kubeStateMetrics[name] for name in …
```
> Fix: the namespace in Url of Prometheus datasource

- grafana/grafana.libsonnet
Rename datasources secret key to `datasources` as it might contain other sources than just Prometheus, depending on user configuration (f.ex. Loki could be included).
> Rename secret key to better describe its contents

- grafana/grafana.libsonnet
Changes the deployment kind from apps/v1beta2 to apps/v1 in order to be compatible with kube 1.16
tested in https://github.com/pschulten/kube-prometheus/commit/eb0c975f7909e017e15fe756723aa6a89e8a39b5
> use proper deployment kind

- .travis.yml
- Makefile
- grafana/grafana.libsonnet
when has non-ascii in config, std.base64 will failed.
e.g. bind_dn with Chinese in ldap.toml.
https://github.com/google/jsonnet/issues/575
https://github.com/google/jsonnet/pull/577
> add non-ascii base64 support

- grafana/grafana.libsonnet
So we have more than 66 dashboards and they are all raw JSON. exported from Grafana UI.
and it takes around 20 min to deploy grafana because of that.  And the culprit is this
https://github.com/brancz/kubernetes-grafana/blob/master/grafana/grafana.libsonnet#L52 (std.manifestJsonEx($._config.grafana.dashboards[name], '    ') }) ).
To indent json its taking whole lot of time. and its eaisly reproducible(just add 3-4 dashboard and you will see an increase in jsonnet time).
So to solve that problem for raw JSON dashboards I have added a new field called `rawGrafanaDashboards` which expects raw JSON value(string JSON value). so insisted of using `import` for this kind of dashboard just use `importstr`
```
'k8s-cluster-dashboard-thanos.json': (importstr 'thanos/all-nodes.json'), …
```
> Improve Performance incase of raw Json from grafana is added

- grafana/grafana.libsonnet
Fix for #79 
Do not create grafana-rawDashboardDefinitons.yaml when rawDashboards is empty. 
All imported raw dashboards will be added to a configmap list.
> Fix grafana-rawDashboardDefinitions file

- grafana/grafana.libsonnet
I think it's good practice to have this set along with the user. I had to set it anyway to make the token provided by IRSA readable in AWS EKS.
> Add fsGroup to securityContext

- README.md
- examples/basic-with-image-renderer.jsonnet
- examples/basic-with-mixin.jsonnet
- examples/basic.jsonnet
- examples/custom-ini.jsonnet
- examples/dashboard-definition.jsonnet
- examples/dashboard-folder-definition.jsonnet
- examples/plugins.jsonnet
- grafana/grafana.libsonnet
- grafana/jsonnetfile.json
Start using absolute import paths to be able to disable legacy imports in projects import this one.
https://github.com/prometheus-operator/kube-prometheus/pull/675
> Use absolute jsonnet imports

- README.md
- examples/basic-with-image-renderer.jsonnet
- examples/basic-with-mixin.jsonnet
- examples/basic.jsonnet
- examples/custom-ini.jsonnet
- examples/dashboard-definition.jsonnet
- examples/dashboard-folder-definition.jsonnet
- examples/plugins.jsonnet
- grafana/grafana.libsonnet
- grafana/jsonnetfile.json
ksonnet isn't needed anymore, going forward.
I tested these new objects by generating a YAML diff with the old output vs the new ones.
> Restructure to not use ksonnet

- grafana/grafana.libsonnet
By annotation dashboard definitions md5, changing dashboard definitions triggers redeployment.
Close https://github.com/brancz/kubernetes-grafana/issues/106.
> Add dashboard definitions md5 to deployment annotations

- grafana/grafana.libsonnet
Container runtimes try to pull unqualified images 
from a list of registries in `/etc/containers/registries.conf`.
An attacker can claim to be `grafana` on a registry
that comes before `docker.io` in the list, which leads to
pulling an unexpected image.
> Use full URL of the image

- grafana/grafana.libsonnet
According to #102 the switch to NodePort was a mistake, this PR reverts it back to it's default value : ClusterIP.
Closes #102
> Revert the service type back to it's default (ClusterIP)

- grafana/grafana.libsonnet
To fix the warning
```
spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
```
@brancz @paulfantom Please review
> grafana/grafana.libsonnet: Update nodeSelector label to kubernetes.io/os

- grafana/grafana.libsonnet
When running a deployment with more that one replica, the generated dashboard folder UIDs can be different per instance. This creates inconsistent behavior when using the "Go to folder" links in `/dashboards/` as, depending on which instance the request hits, the user might get a "Folder not found" error.
The new `folderUidGenerator` function can be overriden to generate consistent folder UIDs by setting `folderUid` in the dashboard provider (docs [here][docs], example below). The default behavior of not setting a UID was maintained to not break expectations.
Additionally, I noticed while testing this feature that Grafana only loads the dashboard providers on startup, so I added a checksum for the providers configmap.
```jsonnet
local grafana = import 'grafana/grafana.libsonnet';
local …
```
> Allow setting folderUid

- grafana/grafana.libsonnet
[std.encodeUTF8][docs] returns an array and the secret expects a string.
This fix should address https://github.com/prometheus-operator/kube-prometheus/issues/1356
[docs]: https://jsonnet.org/ref/stdlib.html#encodeUTF8
> Fix secrets stringData generation

- README.md
- examples/basic-with-image-renderer.jsonnet
- examples/basic-with-mixin.jsonnet
- examples/basic.jsonnet
- examples/custom-ini.jsonnet
- examples/dashboard-definition.jsonnet
- examples/dashboard-folder-definition.jsonnet
- examples/plugins.jsonnet
- grafana/grafana.libsonnet
Refactoring code to use newer design pattern and making it a bit cleaner.
This is a result of kube-prometheus refactor and a follow-up to fix https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/components/grafana.libsonnet#L24.
Additionally now `dashboardDefinitions` are rendered as ConfigMapList to allow easier usage in kubernetes.
> Rewrite code to use newer design pattern.

- grafana/grafana.libsonnet
Part of initiative to increase security of kube-prometheus (https://github.com/prometheus-operator/kube-prometheus/issues/1589)
> Disable automounting SA token

- grafana/grafana.libsonnet
This is part of the initiative to tighten security in kube-prometheus
We're reducing the attack surface by dropping all Linux capabilities since Grafana doesn't need any to run smoothly
Following remediation docs from https://hub.armo.cloud/docs/c-0055
> grafana.libsonnet: Drop all linux capabilities

- grafana/grafana.libsonnet
This is part of the initiative to tighten security in kube-prometheus - prometheus-operator/kube-prometheus#1595.
An attacker who has access to a container, can create files and download scripts as he wishes, and modify the underlying application running on the container. If a container, e.g. grafana, needs to write to the filesystem, a strict volume mount should be used.
Following remediation docs from https://hub.armo.cloud/docs/c-0017
> jsonnet: Forbid write access to root filesystem
